### ISSUE TITLE
plugins settings not working in tinymce

### ISSUE THREAD

**Issue by rejayi-experion** [siegerx3/angular-tinymce#10]
I have provide the settings input as follows but the plugins like textcolor, colorpicker etc are not working
{
      height: 250,
      plugins: [
        "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
        "table contextmenu directionality emoticons template textcolor paste fullpage textcolor colorpicker textpattern"
      ],
      toolbar1: "bold italic underline strikethrough |styleselect formatselect fontselect fontsizeselect",
      toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | insertdatetime preview | forecolor backcolor",
      toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | visualchars visualblocks nonbreaking template pagebreak restoredraft",
      menubar: false,
      toolbar_items_size: 'small',
      resize:false
    }

**Comment by rejayi-experion** [comment]
Issue solved provide plugin links insise the script:[] in angular.cli as
"../node_modules/tinymce/plugins/textcolor/plugin.min.js"

**Comment by siegerx3** [comment]
did you include the plugin's js files in your angular-cli.json or whatever build you're using?
