### ISSUE TITLE
Doesnt work when used twice on the same page

### ISSUE THREAD

**Issue by martinwoitzik** [siegerx3/angular-tinymce#3]
Hi,
I'm using the angular-tinymce component twice on the same page. Every component is bound to a separate ngModel. When updating these models via controller, the second component displays the content of the first one. Maybe this has to do with the iframe inside each component? 
It's a really strange behaviour. It does not happen, when I'm manually inserting text to one of the components?!? 

Cheers
Martin

**Comment by siegerx3** [comment]
I'm using multiple components on the same page and it works fine. Maybe you could provide me with a bit of your code as an example?
