### ISSUE TITLE
Cannot read property 'toRgb' of undefined

### ISSUE THREAD

**Issue by JoeOwner** [siegerx3/angular-tinymce#35]
Hi all,
I'm using the table plugin and when I try and update a border or background color from the table properties popup, I get an"Uncaught TypeError: Cannot read property 'toRgb' of undefined" error the console. 

Thanks

**Comment by siegerx3** [comment]
Hey!
I've completely missed your issue over all the greenkeeper bullshit.
This issues seems more like a problem with tinymce itself though.

But you've probably already figured something out :)
