### ISSUE TITLE
The value change is triggered only on keypress event

### ISSUE THREAD

**Issue by ktriek** [siegerx3/angular-tinymce#5]
Selecting an image or editing in source code mode doesn't update the ` input` value

![image](https://user-images.githubusercontent.com/4461059/32568407-25378304-c48c-11e7-9514-a26f33773682.png)

**Comment by dottodot** [comment]
Yes I'm seeing the same issue with reactive form. If I insert an image and don't do anything else the value isn't updated, I have to type some text to get it to update the value.

**Comment by siegerx3** [comment]
What a coincidence. I just ran into the same issues today. 
I'm gonna have a look.
