### ISSUE TITLE
InsertContent

### ISSUE THREAD

**Issue by GoNode5** [siegerx3/angular-tinymce#7]
Any guidance how to do InsertContent. I want to insert contect at caret position from outside of the component?
(Thanks for your work !!!)

**Comment by siegerx3** [comment]
Since this is just a wrapper around the native tinymce
[this](https://stackoverflow.com/questions/22976974/tinymce-insert-content) should work just fine.

If not, i'm happy to help.

**Comment by GoNode5** [comment]
@siegerx3 You're right, I took the @ViewChild with this.editor.editor.execCommand('mceInsertContent', false, 'your content');  road.

**Comment by thiag0** [comment]
For anyone struggling with this, here is the syntax for getting a reference using @ViewChild.

@ViewChild(EditorComponent, null) editorComponent!: EditorComponent;

The example in the GitHub project sets the 2nd option as "{ static: false }", which was causing editorComponent to be undefined. Not sure if it's specific to my setup, but thought I would share.
